### ISSUE TITLE
Provide reset settings to default

### ISSUE THREAD

**Issue by snowman** [hewenguang/circle#10]
### Suggestions
- [ ] 1. Provide reset settings to default (workaround: reinstall)
- [ ] 2. Import/Export settings, or provide editable area like <textarea> for change 
         settings (backup/import by copy/paste)
- [ ] 3. Run in batch mode (command line, given URLs, output PDFs), this should be the lowest priority
- [ ] 4. Add English README.md (like https://github.com/brookhong/Surfingkeys
- [ ] 5. Add more [GitHub Topics](https://github.blog/2017-01-31-introducing-topics/) to earn more publicity, like `Chrome extension` etc, i dunooo, oh how about copy them from https://github.com/brookhong/Surfingkeys

### Some thought
(ignore this freely)
<pre>
Highlight text with colors (regexp support):

    Especially useful for text that shows many times and long,
    like people name, location, jargon, etc

UI (scratch):

      1. Provide a list of words with borders around sorted by
         occurrences (exclude stop words), Click to toggle highlight
         the selected word.

      2. In another area, show the user's custom patterns list.

      3. Highlight text directly from user input, for example, text
         with space "foo bar", or other regexp patterns

      4. Option to automatically highlight top-N words with most
         occurrences.
</pre>

##### Do you think it's gaudy?
[Code Cleanup: Splitting Up git Commits In the Middle of a Branch - Embedded Artistry](https://embeddedartistry.com/blog/2018/02/19/code-cleanup-splitting-up-git-commits-in-the-middle-of-a-branch/)
![image](https://user-images.githubusercontent.com/16096559/110093763-0bd65000-7dd6-11eb-8737-0e8833cf7105.png)
[Difference Between SMTP and IMAP | Difference Between](http://www.differencebetween.net/technology/protocols-formats/difference-between-smtp-and-imap/)
![image](https://user-images.githubusercontent.com/16096559/110095246-ac793f80-7dd7-11eb-9582-41736f130df9.png)

#### Hopes Circle becomes on the up-and-up :)

**Comment by hewenguang** [comment]
Thanks for the feedback. My English ability is not good, so I don’t have an English version of the readme. I will join it later. Regarding the proposed features, I will consider whether to add

**Comment by hewenguang** [comment]
The new version has been released: the chrome market is still under review, and the packages that can be installed (reduced to 69kb) are shown in: https://ranhe.xyz/post-images/circle.zip

Reset settings have been added. Other functions will be considered later
