### ISSUE TITLE
在浏览使用了 Pjax 技术的网站时出错

### ISSUE THREAD

**Issue by spirit1431007** [hewenguang/circle#11]
**遇到的问题**:

在浏览部分使用了Pjax技术的网页时，可能会出现块个问题
1. 着陆页为首页，点进文章，点击Circle进入阅读模式，无法识别正文
2. 点击Circle进入阅读模式，退出Circle，进入该网站的另一篇文章，点击Circle进入阅读模式，此时显示的还是之前的文章
3. 标题识别错误

**你期望的结果**:

页面内容更新时，Circle能自动更新标题及正文

**复现网址**:

https://iiong.com 
https://haremu.com 
https://www.ihewro.com

**Comment by hewenguang** [comment]
新版本已经发布： chrome 市场还在审核，可以安装的包（缩小到了 69kb）见：https://ranhe.xyz/post-images/circle.zip

其中 https://haremu.com 因为网站太酷炫，目前暂时无法解决。后期会继续优化算法支持
