### ISSUE TITLE
无法在阅读模式中使用 element.scrollIntoView() 或者 window.scrollTo({top: 1000})

### ISSUE THREAD

**Issue by snowman** [hewenguang/circle#12]
**遇到的问题**:
无法在`阅读模式`中使用 `element.scrollIntoView()` 或者 `window.scrollTo({top: 1000})`

**复现网址**:
https://ranhe.xyz/my-career/

**Comment by hewenguang** [comment]
问题已经收到。方便的话可以加 QQ 群 605710052 参与讨论

**Comment by hewenguang** [comment]
新版本已经发布： chrome 市场还在审核，可以安装的包（缩小到了 69kb）见：https://ranhe.xyz/post-images/circle.zip
