### ISSUE TITLE
建议增加无图模式

### ISSUE THREAD

**Issue by PaulHerrero** [hewenguang/circle#14]
希望可以一键切换成无图模式

**Comment by hewenguang** [comment]
你好，这个的使用场景在哪里？？我没有 get 到使用场景

**Comment by PaulHerrero** [comment]
你好，许多文章的配图其实与文章内容没有必要的联系，仅仅是为了配图而配图，尤其是一些微信文章，不如屏蔽了更清爽

**Comment by hewenguang** [comment]
了解了，我后面加上配置

**Comment by PaulHerrero** [comment]
感谢

**Comment by greatoe** [comment]
但请保留有图模式...

**Comment by hewenguang** [comment]
> 但请保留有图模式...

好的，目前打算默认是有图，可以切换成无图模式，满足更多用户需求

**Comment by hewenguang** [comment]
加入计划中 https://github.com/hewenguang/circle/issues/1
