### ISSUE TITLE
有网站未配适

### ISSUE THREAD

**Issue by PaulHerrero** [hewenguang/circle#17]
**遇到的问题**: 点击扩展不能进入阅读模式

**你期望的结果**: 希望能够配适，进入阅读模式

**复现网址**: https://www.playpcesor.com/2021/02/OpenSyllabus.html

**Comment by hewenguang** [comment]
chrome 版本已经发布，其他平台审核过程中。识别算法从 9kb 减小到了 5kb ，但识别能力更强大，识别效果更好。上面反馈类似网页全部适配
