### ISSUE TITLE
微信公众号文章中的代码格式有误

### ISSUE THREAD

**Issue by Ming-Lei** [hewenguang/circle#18]
比如[这个网页](https://mp.weixin.qq.com/s?src=11&timestamp=1615358751&ver=2937&signature=*J2zBp*E-CYEO7YQLFG7hcLWUnnz45vL2zRA97dFh6SXcjfYCLQ3Zq7ZHmlq*cIugVHHrhlX*5qVIIQxNRyLyhQHfosgWtV9InobRfR84cgNRmfi35Ox55BCqZ7Ysfc2)

转换之前是这样的

![image](https://user-images.githubusercontent.com/12847499/110589983-20d62900-81b2-11eb-93a7-439070213feb.png)

转换后格式就会乱掉

![image](https://user-images.githubusercontent.com/12847499/110590065-3f3c2480-81b2-11eb-9a5f-0adfcf06fb3a.png)

Python代码非常依赖缩进，影响很大，希望能修复下这个问题

**Comment by hewenguang** [comment]
公式和代码还没有进入开发，后期会处理

**Comment by hewenguang** [comment]
文章被删，无法验证修复效果。新版对代码格式做了部分兼容，不会丢失空格了。但代码高量等特性还没有时间开发

chrome 版本已经发布，其他平台审核过程中

可以更新试试效果，感谢支持和反馈
