### ISSUE TITLE
影响验证码刷新

### ISSUE THREAD

**Issue by xuehaiwuyakuzuozou** [hewenguang/circle#19]
**遇到的问题**:首次输入验证码，报错验证吗错误，再次输入新的验证码，成功登录。注销，输入验证码，报错验证码错误，再次输入成功登录。
**问题截图**:内部系统不能截图

**你期望的结果**:

**复现网址**:

**Comment by hewenguang** [comment]
可以找一个相似网站吗？我这边没有复现成功

**Comment by lemako** [comment]
我也有发现了这个bug，太可惜了，真的很喜欢这个扩展。
[https://i.imgur.com/vXpuM5y.gif](url)
但我这个网站也是个私密网站，也不能给你网址。

所以只能给你截图了 关闭扩展一切正常

**Comment by hewenguang** [comment]
好的，感谢。我研究下

**Comment by hewenguang** [comment]
chrome 版本已经发布，其他平台审核过程中。识别算法从 9kb 减小到了 5kb ，但识别能力更强大，识别效果更好。修改全部实现逻辑，解决了上面的问题
