### ISSUE TITLE
关于页面识别失败评论在这里

### ISSUE THREAD

**Issue by hewenguang** [hewenguang/circle#2]
针对正常的大篇幅文章识别失败，无法正常展示情况。请在下面评论。我会在处理之后回复，感谢反馈

写上对应失败网址！写上对应失败网址！写上对应失败网址！

**Comment by chiahsien** [comment]
請問它有支援 Brave 瀏覽器嗎? 我在 Brave 安裝它，雖然有些網站被判定有支援(變成綠色圈圈)，可是點下去之後頁面卻是一片空白。

**Comment by hewenguang** [comment]
> 請問它有支援 Brave 瀏覽器嗎? 我在 Brave 安裝它，雖然有些網站被判定有支援(變成綠色圈圈)，可是點下去之後頁面卻是一片空白。

已经加入功能规划里 https://github.com/hewenguang/circle/issues/1

**Comment by snowman** [comment]
http://new.rushi.net/Home/Works/mobilework/id/50657.html

这个是正常的吗? 文字没有换行

![image](https://user-images.githubusercontent.com/16096559/110084563-10e1d200-7dcb-11eb-9610-dad425d186b2.png)

**Comment by hewenguang** [comment]
> http://new.rushi.net/Home/Works/mobilework/id/50657.html
> 
> 这个是正常的吗? 文字没有换行
> 
> ![image](https://user-images.githubusercontent.com/16096559/110084563-10e1d200-7dcb-11eb-9610-dad425d186b2.png)

收到，我会跟进

**Comment by spirit1431007** [comment]
https://www.fanhaobai.com/2020/12/hexo-to-docker.html
无法识别正文

**Comment by hewenguang** [comment]
> https://www.fanhaobai.com/2020/12/hexo-to-docker.html
> 无法识别正文

收到，我研究研究

**Comment by hewenguang** [comment]
> https://www.fanhaobai.com/2020/12/hexo-to-docker.html
> 无法识别正文

新版本已经发布： chrome 市场还在审核，可以安装的包（缩小到了 69kb）见：https://ranhe.xyz/post-images/circle.zip

**Comment by hewenguang** [comment]
经过全新设计和全新重构的 Circle v2.0.0 正式版本已上线，欢迎使用。新版本上线了大量易用性功能，包括但不限于代码高亮、白名单、黑名单、跟随系统自动切换主题、本地 markdown 文件支持、快捷键、右键菜单、自定义样式等等大量功能统统支持，欢迎下载体验
