### ISSUE TITLE
希望支持firefox

### ISSUE THREAD

**Issue by colinxu2020** [hewenguang/circle#20]
使用[firefox开发者](https://addons.mozilla.org/zh-CN/developers)创建的扩展程序无法使用(是这个issue发布时的最新版本)

**Comment by colinxu2020** [comment]
可在[简书](https://www.jianshu.com/p/417cd1989781) [起点中文网](https://read.qidian.com/chapter/fM9duSAfNlBmzDX0o03xsg2/pxXB6FdLmkdp4rPq4Fd4KQ2) 等网站复现

**Comment by hewenguang** [comment]
目前根据大家的反馈情况，已经开始上架其他平台了。firfox 存在技术问题，还在排查。相信不久 Circle 就会出现在各个浏览器扩展市场

**Comment by colinxu2020** [comment]
firefox似乎不会自动调用 'client/index.js'

**Comment by hewenguang** [comment]
是一些 api 的区别，这个需要调试，目前在firefox 无法直接运行，其他浏览器都是可以直接运行的

**Comment by colinxu2020** [comment]
firefox开发者中的检查通过了且上传成功
![image](https://user-images.githubusercontent.com/63941938/110772637-c82c8c00-8296-11eb-8a99-24cec9b6afe0.png)

**Comment by hewenguang** [comment]
加微信聊： hewenguang_fe

**Comment by colinxu2020** [comment]
可以发邮件吗? colinxu2020@gmail.com

**Comment by hewenguang** [comment]
已经提交火狐市场审核

**Comment by hewenguang** [comment]
进入[Microsoft Edge 浏览器扩展市场](https://microsoftedge.microsoft.com/addons/detail/circle-%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F%EF%BD%9Creader-mode/hjkjecmcifblnghjpcjaofpakjpgfjio) 安装

进入[Firefox 浏览器扩展市场](https://addons.mozilla.org/zh-CN/firefox/addon/circle-reading-mode/) 安装

进入[Chrome 浏览器扩展市场](https://chrome.google.com/webstore/detail/circle-reader-mode/dhpfcgilccfkodnhbllpiaabofjbjcbg)下载
