### ISSUE TITLE
百度百科的页面适配的非常不好，文字大小，文字排版，尤其是图片位置和段落位置，希望作者能改进一下，谢谢作者。

### ISSUE THREAD

**Issue by rainseason1** [hewenguang/circle#21]
百度百科的页面适配的非常不好，文字大小，文字排版，尤其是图片位置和段落位置，希望作者能改进一下，谢谢作者。

**Comment by hewenguang** [comment]
好的

**Comment by hewenguang** [comment]
chrome 版本已经发布，其他平台审核过程中。由于 百度百科采用大量定位实现展示效果，小版本无法修复，需要后面迭代几个版本才能搞定，这个 issue 暂时关闭，感谢反馈
