### ISSUE TITLE
重排微信公众号文章会出现正文缺失的问题

### ISSUE THREAD

**Issue by zhengyu** [hewenguang/circle#24]
**遇到的问题**:
总结后面的段落不见了

**复现网址**:
https://mp.weixin.qq.com/s/zbcMXoJLG2ied3Ei82noaA

**Comment by hewenguang** [comment]
感谢反馈，后面我会优化算法

**Comment by hewenguang** [comment]
chrome 版本已经发布，其他平台审核过程中。识别算法从 9kb 减小到了 5kb ，但识别能力更强大，识别效果更好。上面反馈类似网页全部适配
