### ISSUE TITLE
能不能自定义快捷键？

### ISSUE THREAD

**Issue by small32** [hewenguang/circle#25]
**遇到的问题**:目前默认是双击C键自动切换到阅读模式

**问题截图**:

**你期望的结果**:能不能自定义成别的键？有时候ctrl + C，但是相信很多人像我一样都会不自觉地按住ctrl，然后多按几次C，这样忽然就切换到阅读模式了，很烦

**复现网址**:

**Comment by lfk0** [comment]
+1
我这边是ctrl+c两次发送选中的单词到词典程序查询，然后每次都进了阅读模式……

**Comment by hewenguang** [comment]
已经加入功能规划中

**Comment by hewenguang** [comment]
chrome 版本已经发布，其他平台审核过程中。除了加入自定义快捷键还加入了返回顶部和文章目录显示（设置页面启用）等等，欢迎试用
