### ISSUE TITLE
thenewstack.io 目前无法使用

### ISSUE THREAD

**Issue by gt-sun** [hewenguang/circle#26]
**遇到的问题**:  网站不能适配

**问题截图**:

**你期望的结果**:

**复现网址**:  https://thenewstack.io/containerds-important-role-for-nvidias-gpu-operator-and-ai-accelerated-cloud/

**Comment by hewenguang** [comment]
收到，我会怕查原因

**Comment by hewenguang** [comment]
好的，收到了。类似结构网站适配效果不好。正在优化算法，下个版本全部适配，感谢反馈

**Comment by hewenguang** [comment]
chrome 版本已经发布，其他平台审核过程中。识别算法从 9kb 减小到了 5kb ，但识别能力更强大，识别效果更好。上面反馈类似网页全部适配
