### ISSUE TITLE
网站未配适

### ISSUE THREAD

**Issue by PaulHerrero** [hewenguang/circle#27]
**遇到的问题**: 网站未配适

**问题截图**:

**你期望的结果**: 进入阅读模式

**复现网址**: https://www.thepaper.cn/

**Comment by hewenguang** [comment]
好的，收到了。类似结构网站适配效果不好。正在优化算法，下个版本全部适配，感谢反馈

**Comment by hewenguang** [comment]
chrome 版本已经发布，其他平台审核过程中。识别算法从 9kb 减小到了 5kb ，但识别能力更强大，识别效果更好。上面反馈类似网页全部适配
