### ISSUE TITLE
页内跳转支持

### ISSUE THREAD

**Issue by jackfrostzj** [hewenguang/circle#28]
原网页支持href和id页内跳转，circle模式下希望保留href、id并支持跳转

eg：https://w.cnblogs.com/timlly/p/11471507.html?utm_source=wechat_session&utm_medium=social&utm_oi=895719691941736448

**Comment by hewenguang** [comment]
chrome 版本已经发布，其他平台审核过程中。加入文章目录展示（需要后台设置开启）
