### ISSUE TITLE
输入CC 会自动进入阅读模式

### ISSUE THREAD

**Issue by Attiv** [hewenguang/circle#29]
**遇到的问题**:
输入CC 会自动进入阅读模式
**问题截图**:

**你期望的结果**:
输入CC 不会自动进入阅读模式
**复现网址**:
任何支持阅读模式的

双拼一打cc 就进入阅读模式，很难受

**Comment by hewenguang** [comment]
收到，下个版本会修复

**Comment by hewenguang** [comment]
chrome 版本已经发布，其他平台审核过程中。已经对输入和复制操作进行了处理，同时支持自定义快捷键
