### ISSUE TITLE
打印设置优化

### ISSUE THREAD

**Issue by xfish33** [hewenguang/circle#3]
**遇到的问题**:打印重新排版的页面时，标题、功能按键会在各页重复出现

**你期望的结果**:标题不重复出现，功能按键不显示

**Comment by hewenguang** [comment]
麻烦提供截图和相对应的网址，方便定位问题

**Comment by xfish33** [comment]
只要是circle支持的网页都存在这个问题，示意性的网址为http://baijiahao.baidu.com/s?id=1693200275308866754
截图如下：
![image](https://user-images.githubusercontent.com/59218070/109930755-f80de980-7d02-11eb-943a-083cbd53d4cb.png)

使用Edge或Chrome，按Ctrl+P打印，保存为pdf时，标题和控件都会重复出现在页首，类似页眉一样存在

**Comment by hewenguang** [comment]
下个版本上！！！话说支持 Edge ？？？

**Comment by xfish33** [comment]
亲自的Edge就是换壳的Chrome
辛苦了，希望越做越好

**Comment by snowman** [comment]
- [ ] 1. 希望 加个 打印 按钮, 点击 弹出 浏览器 内置 打印页面
   有些电脑新手可能不知道 `Ctrl-P`, 就像 全屏按钮 一样, 直接 按 `F11` 开启 全屏模式

- [ ] 2. 第一页 和 第二页 是 重复的内容, 此时在阅读页面没有任何的滚动
https://embeddedartistry.com/blog/2018/02/19/code-cleanup-splitting-up-git-commits-in-the-middle-of-a-branch/

![page_0_with_border](https://user-images.githubusercontent.com/16096559/110082899-f1e24080-7dc8-11eb-8a9e-78dc338cc07d.png)


![page_1](https://user-images.githubusercontent.com/16096559/110082724-b5164980-7dc8-11eb-893c-6cf5097bf0f8.png)
![page_2](https://user-images.githubusercontent.com/16096559/110082725-b5aee000-7dc8-11eb-830f-3d2afdea852c.png)

- [ ] 3.如果在阅读页面(非打印预览)继续向下滚动的话, 会刷出下一篇文章? 提示 `"The next page is parsed successfully, and the automatic loading starts"`

**Comment by hewenguang** [comment]
paper effect 其实就是”纸张效果“ 也就是有一个白色背景的框，也就是默认的效果。启用后就没有框了，全是白色背景。这个我没有想到啥好的说明。你如果有好的文案，欢迎指教

对于你上面提出的问题，我会一一查看和处理的。Circle 的成长，离不开像你这样的人，感谢

**Comment by hewenguang** [comment]
新版本已经发布： chrome 市场还在审核，可以安装的包（缩小到了 69kb）见：https://ranhe.xyz/post-images/circle.zip

纸张效果见

![image](https://user-images.githubusercontent.com/38025280/110466974-668ee500-8111-11eb-828b-9ec6bf87edd6.png)
