### ISSUE TITLE
连按F键的快捷功能可以关闭吗？

### ISSUE THREAD

**Issue by pauff** [hewenguang/circle#30]
**遇到的问题**: 在浏览网页时连按F键会弹出聚焦页面元素的功能，非常打扰上网体验。（应该是circle插件造成的吧？）也不清楚这是个什么feature。

**问题截图**:
![Uploading Xnip2021-04-01_10-48-36.jpg…]()

**Comment by hewenguang** [comment]
这个是聚焦模式，下一个版本可以设置关闭快捷键

**Comment by hewenguang** [comment]
chrome 版本已经发布，其他平台审核过程中
