### ISSUE TITLE
点击目录时目录背景不跟随，页面设置选项过长在小屏上无法查看。

### ISSUE THREAD

**Issue by SylleoYr** [hewenguang/circle#31]
**遇到的问题**:

1. 鼠标点击目录跳转时，页面发生跳转但目录不跟随，背景颜色无变化。（鼠标滚动时有）
2. 阅读页面设置选项过长时不能滚动，超出部分无法查看。

**问题截图**:

![toc](https://user-images.githubusercontent.com/23133978/115486958-4747b380-a28a-11eb-910a-47dff9fd8b7f.png)
![settings](https://user-images.githubusercontent.com/23133978/115486962-4c0c6780-a28a-11eb-98f6-84d6d274b133.png)

**你期望的结果**:

1. 鼠标点击目录跳转时目录跟随变化
2. 阅读页面的设置选项可滚动查看

**复现网址**:

https://sspai.com/post/66102#circle-heading-2

**Comment by hewenguang** [comment]
下个版本处理

**Comment by hewenguang** [comment]
经过全新设计和全新重构的 Circle v2.0.0 正式版本已上线。新版本修复了这个问题。上线了大量易用性功能包括但不限于代码高亮、白名单、黑名单、跟随系统自动切换主题、本地 markdown 文件支持、快捷键、右键菜单、自定义样式等等大量功能统统支持，欢迎下载体验
