### ISSUE TITLE
需要黑名单功能

### ISSUE THREAD

**Issue by heptaspirit** [hewenguang/circle#32]
**遇到的问题**: firefox平台使用中时，部分网页会莫名卡顿，同时浏览器提示“扩展应用circle拖慢了网页”

**问题截图**:

**你期望的结果**: 

1. 希望能增加黑名单的功能，指定部分网站不会去尝试检测开启

**复现网址**:

**Comment by hewenguang** [comment]
经过全新设计和全新重构的 Circle v2.0.0 正式版本已上线。新版本上线了大量易用性功能，包括但不限于代码高亮、白名单、黑名单、跟随系统自动切换主题、本地 markdown 文件支持、快捷键、右键菜单、自定义样式等等大量功能统统支持，欢迎下载体验
