### ISSUE TITLE
能否增加一个支持自定义CSS的功能。

### ISSUE THREAD

**Issue by zhu1979** [hewenguang/circle#33]
**遇到的问题**:
stylish设置的CSS不起作用了

**问题截图**:

**你期望的结果**:

**复现网址**:

**Comment by hewenguang** [comment]
经过全新设计和全新重构的 Circle v2.0.0 正式版本已上线。新版本不仅包含自定义样式，还上线了大量易用性功能，包括但不限于代码高亮、白名单、黑名单、跟随系统自动切换主题、本地 markdown 文件支持、快捷键、右键菜单等等大量功能统统支持，欢迎下载体验
