### ISSUE TITLE
什么值得买文章页，链接块解析异常

### ISSUE THREAD

**Issue by Fiki6640** [hewenguang/circle#35]
**遇到的问题**:链接块解析异常

**问题截图**:
![image](https://user-images.githubusercontent.com/19770172/121131261-18999280-c862-11eb-95a0-d557e3063fc6.png)

**你期望的结果**:
![image](https://user-images.githubusercontent.com/19770172/121131239-120b1b00-c862-11eb-98b6-94cde66aa2a0.png)

**复现网址**:
https://post.smzdm.com/p/az5gwonr/

**Comment by hewenguang** [comment]
经过全新设计和全新重构的 Circle v2.0.0 正式版本已上线，欢迎使用。新版本对渲染引擎进行了重构，同时上线了大量易用性功能，包括但不限于代码高亮、白名单、黑名单、跟随系统自动切换主题、本地 markdown 文件支持、快捷键、右键菜单、自定义样式等等大量功能统统支持，欢迎下载体验
