### ISSUE TITLE
Chrome提示 circle网页阅读助手 被禁用

### ISSUE THREAD

**Issue by artxia** [hewenguang/circle#36]
chrome 版本 91.0.4472.114（正式版本） (x86_64)

**遇到的问题**:

**问题截图**:
![image](https://user-images.githubusercontent.com/50513568/123988841-ef03ff00-d9fa-11eb-8585-dc66e0f29d74.png)

**你期望的结果**:

**复现网址**:

**Comment by hewenguang** [comment]
本次更新上线了导入配置功能，需要使用下载权限，开启即可

xia ***@***.***> 于2021年6月30日周三 下午11:30写道：

**Comment by hewenguang** [comment]
本次更新上线了导入配置功能，需要使用下载权限，开启即可
