### ISSUE TITLE
只开源了外壳么?

### ISSUE THREAD

**Issue by zohar-soul** [hewenguang/circle#37]
没有找到 `自研的正文解析引擎` 这个相关的代码

**Comment by hewenguang** [comment]
对这块算法感兴趣可以看 https://ranhe.xyz/wang-ye-zheng-wen-ti-qu-suan-fa-yan-jiu-xue-xi/

**Comment by jianglinyang8** [comment]
只开源了外壳。。。。。

**Comment by hewenguang** [comment]
感兴趣可以看这个，里面包含了源代码

https://ranhe.xyz/wang-ye-zheng-wen-ti-qu-suan-fa-yan-jiu-xue-xi/

**Comment by jianglinyang8** [comment]
> 感兴趣可以看这个，里面包含了源代码 https://ranhe.xyz/wang-ye-zheng-wen-ti-qu-suan-fa-yan-jiu-xue-xi/ Message ID: ***@***.***>
> […](#)

这链接只是一些简单的介绍，但是没有看到作者的超级轻量化代码是怎么实现比别人优秀的
