### ISSUE TITLE
circle阅读模式的启用问题

### ISSUE THREAD

**Issue by laiqun** [hewenguang/circle#38]
**遇到的问题**:
circle阅读模式的启用似乎检测了Dom 是否加载完成.
补充一个场景,当浏览的页面里面有引用google 和Facebook的统计脚本之类的东西,页面就会一直加载不完.

**问题截图**:

**你期望的结果**:
是否可以考虑设置一个超时时间,用Promise.race,比如10s了,即使没加载完成,也可以启用circle阅读模式.
**复现网址**:
https://dcravey.wordpress.com/2011/03/21/using-sqlite-in-a-visual-c-application/

**Comment by hewenguang** [comment]
很好的建议，下个版本我会加上
