### ISSUE TITLE
期待新功能

### ISSUE THREAD

**Issue by SagacitySucura** [hewenguang/circle#39]
**遇到的问题**:单纯想要打印的时候网页能显示完全，好像这个功能还没有

**问题截图**:

**你期望的结果**:

**复现网址**:

**Comment by hewenguang** [comment]
不太理解什么意思，可以详细说说吗？

**Comment by SagacitySucura** [comment]
就是说比如我想打印知乎的文章，直接打印肯定就是片段缺失了，您这个插件也很棒，内容可以完全显示，但是就是公式部分容易错位，如果能够不改变网页布局的前提下只是切割就好了，哈哈，我就是随便想象下，可能会很难做到吧

**Comment by hewenguang** [comment]
明白了，你的意思是不动原网页，直接删除其他元素

孙立望 ***@***.***> 于2021年11月29日周一 上午11:47写道：

**Comment by hewenguang** [comment]
公式是因为没有支持，如果只是打印原网页部门内容的话，直接找相关的扩展就好了。公式后面会支持，目前还在开发其他的功能

孙立望 ***@***.***> 于2021年11月29日周一 上午11:47写道：

**Comment by hewenguang** [comment]
新版本可以通过“高亮原文”实现，启用“高量原文”后，右键选择 ‘打印“ 即可。
