### ISSUE TITLE
聚焦模式可以有吗

### ISSUE THREAD

**Issue by gt-sun** [hewenguang/circle#4]
其实我用的最多的是聚焦模式，因为不想改变网站原有的布局。 聚焦模式也能起到遮挡广告的效果，并且不需要重新加载页面。

**Comment by hewenguang** [comment]
目前 Circle 还只是一个测试小版本，我会等产品稳定之后支持。已经加入功能规划中：https://github.com/hewenguang/circle/issues/1

**Comment by hewenguang** [comment]
经过全新设计和全新重构的 Circle v2.0.0 正式版本已上线。新版本包含聚焦模式，同时上线了大量易用性功能，包括但不限于代码高亮、白名单、黑名单、跟随系统自动切换主题、本地 markdown 文件支持、快捷键、右键菜单、自定义样式等等大量功能统统支持，欢迎下载体验
