### ISSUE TITLE
這個網頁截取內容錯誤

### ISSUE THREAD

**Issue by naive231** [hewenguang/circle#40]
**遇到的问题**:

[這個網頁](https://www.inside.com.tw/article/3325-59-hilarious-but-true-programming-quotes-for-software-developers)截取內容錯誤。

**问题截图**:

內容錯誤：
![image](https://user-images.githubusercontent.com/650107/145337201-150bcfe2-c67e-48fb-809f-12baeb7a62ec.png)

**你期望的结果**:

應該是這裡面的內容：
![image](https://user-images.githubusercontent.com/650107/145337170-33ba1ff7-163e-4b0f-a314-099320fa7840.png)

**复现网址**:

https://www.inside.com.tw/article/3325-59-hilarious-but-true-programming-quotes-for-software-developers

**Comment by hewenguang** [comment]
网站貌似无法访问了？

**Comment by naive231** [comment]
> 网站貌似无法访问了？

沒有哦，可以訪問，內容一樣：
![image](https://user-images.githubusercontent.com/650107/169691548-af6ce263-d6e3-46f7-a774-38a4f3c326bb.png)

**Comment by hewenguang** [comment]
已修复，更新到最新版本即可
