### ISSUE TITLE
布局里的页内边距为什么只对顶部边距有效？

### ISSUE THREAD

**Issue by clytiee** [hewenguang/circle#41]
我调整页内边距时，只有顶部边距发生变化，左右并没有变化。
这样会造成我打印成pdf时，左右太宽。
能不能修改或者加上调整左右边距的选项？
![issue1](https://user-images.githubusercontent.com/4569511/147814806-84e52b17-a8c9-475b-a07a-a44debc4899e.png)

**Comment by hewenguang** [comment]
新版本 v2.3.0 已修复
