### ISSUE TITLE
没有联系方式吗？比如邮箱？

### ISSUE THREAD

**Issue by snowman** [hewenguang/circle#44]
官网查遍了都没有找到联系方式，只有一个[circle阅读助手 产品交流](https://support.qq.com/products/317910)，而且是在**常见问题**里面的**立即贡献**，但是我不想用这个, 而且太多层跳转了

我没找到邮箱联系方式，能不能把整个**联系方式**独立出来？不要写在[常见问题](http://circlereader.com/support)里面，这个不应该放在**常见问题**里面

比如 新增一栏 **联系我们** 在 导航栏上

好吧， 我找到了[联系我 | Circle 阅读助手](http://www.circlereader.com/contacts), 不过是通过谷歌搜索`site:circlereader.com email`找到的

#### ADDED:

原来在[如何支持 Circle？ | Circle 阅读助手](http://circlereader.com/support)`翻译 Circle`也可以找到邮箱联系方式 :|， 我不想翻译， 只想提报告， 所以忽略掉了...

---
我原来的问题就是：
**更新日志**能不能带上时间戳？:)))

**Comment by hewenguang** [comment]
好的，哈哈哈。对不起没考虑那么全面。我后面加下

**Comment by hewenguang** [comment]
已经按照建议更新到了官网哈
