### ISSUE TITLE
稍后读这个功能是还在实验阶段吗? 很隐蔽。

### ISSUE THREAD

**Issue by godefy** [hewenguang/circle#46]
稍后读功能目前只能先在右键菜单设置里加入到菜单,然后才能通过邮件菜单去使用。没有任何其它的操作入口。
是因为目前这个功能还处于测试阶段,所以还明显的放出来吗?

**Comment by hewenguang** [comment]
稍后读目前是第一个版本，可以通过右键菜单和快捷键呼出。
