### ISSUE TITLE
黑暗模式和浏览器插件冲突的问题

### ISSUE THREAD

**Issue by wyk111wyk** [hewenguang/circle#47]
**遇到的问题**:

近几个版本支持了自动切换黑暗模式的功能，这对阅读体验带来了很大的帮助。
但是最近使用中我发现这和浏览器插件带来的网页反色的功能起了冲突，例如我在用一款叫Dark Mode的插件，功能就是晚上把网页上的所有颜色一反了之，平时用没问题，而一旦开启了阅读模式遇到了自动黑暗模式就会负负得正重新变成了白色底黑色字。
不知道有没有可能在阅读模式这一端做些判断和优化解决这个问题。
谢谢

**问题截图**:

**你期望的结果**:

**复现网址**:

**Comment by hewenguang** [comment]
需要反馈到 Dark Mode 那边，我这边没什么好的方式处理
