### ISSUE TITLE
右键菜单消失

### ISSUE THREAD

**Issue by coldwinds** [hewenguang/circle#48]
**遇到的问题**:

没有右键菜单（设置里已开启）

重现方法 将本扩展取消固定 然后重启浏览器 然后右键菜单就没了 不知道是不是我浏览器的问题

然后在设置里关闭右键菜单 再开启右键菜单 右键菜单又有了

**Comment by hewenguang** [comment]
应该是浏览器新版本的重启没有触发相关的事件，后面我处理下。感谢您的支持，Circle ***@***.***官网：http://circlereader.com

**Comment by LitCcc** [comment]
这个bug居然还没有修复...非常影响使用

**Comment by hewenguang** [comment]
新版本已经修复
