### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by mx4994** [hewenguang/circle#5]
体验了下，排版速度是真的快，就是第一次安装使用的时候，挂代理初始化不成功，提示连接网络重试，关了代理重新加载就正常了。
目前有两个小建议：
1、打开阅读模式添加快捷键支持（你已经有规划了）。
2、排版页设置，添加一个重置为默认参数，因为有时候想自定义调调，都改了之后，又觉得好像没有默认好看，这个时候又全都改回去，有点麻烦，哈哈哈。

其实还有个建议，就是添加长文阅读的对开翻页模式，我个人觉得阅读长文的时候，滚动阅读没有对开翻页来的舒服，效率也不及对开翻页（仅指长文），这方面我觉得做的好的就是多看了，[多看阅读示例](http://www.duokan.com/reader/www/app.html?id=438e00f246c745418494e8ab7a6f933b)当然，只是个建议。
![image](https://user-images.githubusercontent.com/52325833/109915177-52e81680-7cec-11eb-850c-1a3e2765a027.png)

感谢你的工作🤞

**Comment by hewenguang** [comment]
安装慢是因为前期测试阶段，为了快速迭代，常变动代码是初始化阶段从远程拉回来的

关于排版页设置，我觉得可以有，哈哈哈

长文翻页后期会考虑加入，但不是优先级最高的

相关信息已经更新到https://github.com/hewenguang/circle/issues/1 感谢支持

**Comment by hewenguang** [comment]
经过全新设计和全新重构的 Circle v2.0.0
正式版本已上线。新版本上线了大量易用性功能，包括但不限于代码高亮、白名单、黑名单、跟随系统自动切换主题、本地 markdown
文件支持、快捷键、右键菜单、自定义样式等等大量功能统统支持，欢迎下载体验

“对开翻页” 放在了  2.0.1 版本开发，”恢复初始设置“本次已上线

mx4994 ***@***.***> 于2021年3月4日周四 下午1:29写道：
