### ISSUE TITLE
github页面重复刷新

### ISSUE THREAD

**Issue by Briy09** [hewenguang/circle#51]
**遇到的问题**:
在 `github.com` 上点击仓库里的文件夹或文件，会造成页面重复刷新。
比如 点击 [ https://github.com/hewenguang/circle](https://github.com/hewenguang/circle) 里的 `src` 文件夹 ，页面已经加载出来后，马上页面自动又刷新一遍。
关闭扩展此bug消失。

**Comment by hewenguang** [comment]
新版本已经修复了
