### ISSUE TITLE
希望能加入文本文件的功能

### ISSUE THREAD

**Issue by haoxiaoyueh** [hewenguang/circle#56]
**遇到的问题**:不支持本地打开的文本文件

**问题截图**:
![屏幕截图_20230219_223506](https://user-images.githubusercontent.com/113106402/219954940-5667330c-8862-46e8-8c14-84b01521072e.png)
![屏幕截图_20230219_222942](https://user-images.githubusercontent.com/113106402/219954949-1aa16261-78a9-40c4-8dfd-3445b4878a7b.png)
**你期望的结果**:
![期望值](https://user-images.githubusercontent.com/113106402/219955091-902fb7b1-bc1b-43d9-94d9-735610aa3b8d.png)

**复现网址**:
file:///C:/%E5%B0%8F%E8%AF%B4/%E5%B0%8F%E8%AF%B4%E7%9B%AE%E5%BD%95/%E6%88%91%E6%89%93%E9%80%A0%E4%BA%86%E6%97%A7%E6%97%A5%E6%94%AF%E9%85%8D%E8%80%85%E7%A5%9E%E8%AF%9D.txt

**Comment by hewenguang** [comment]
可以参考这个教程设置下即可

**Comment by haoxiaoyueh** [comment]
教程在哪？

**Comment by hewenguang** [comment]
https://circlereader.com/node/28
