### ISSUE TITLE
支持自定义浏览器吗？

### ISSUE THREAD

**Issue by manateelazycat** [hewenguang/circle#6]
您好，染河

今天用了你的 Circle 查看文章，非常棒，感谢你的工作！

我本人是Emacs/EAF的作者 （项目地址 https://github.com/manateelazycat/emacs-application-framework )
EAF里面用PyQt开发了自己的浏览器。

想问一下您的circle库能否像 darkreader.js 那样支持自定义浏览器通过库的方式来使用呢？

如果已经可以了，麻烦告知一下库的使用步骤。 ;)

工作很棒，再次感谢！

**Comment by hewenguang** [comment]
大概看了下产品做的真不错。目前 Circle 只是一个测试版本，后期稳定之后会推出各种平台版本
