### ISSUE TITLE
circle为了简洁阅读，设置却复杂的吓人

### ISSUE THREAD

**Issue by githubcatheaven** [hewenguang/circle#67]
用户是为了页面变简洁用的circle，设置又是一大片有的没的的设置项，是不是很搞笑？
作者真的认真想过设置搞这么多的意义吗？

**Comment by hewenguang** [comment]
为了你这个评论，我心发布了版本，默认把不需要的功能禁用了，然后你又说越改越垃圾，如果真的这么不满意，请卸载。

不明白我日日夜夜的加班到深夜，维护这个产品，基本都是用爱发电，遇到问题正常反馈不行吗？一定要这么暴躁吗？
