### ISSUE TITLE
建议：添加高亮和笔记功能

### ISSUE THREAD

**Issue by Andy-AO** [hewenguang/circle#69]
现在字体大了，排版也可以调了，这个很方便，但是阅读一些严肃的东西，需要记笔记，需要写写画画，希望添加高亮和笔记功能。
目前我是保存成pdf，然后用pdf编辑器做笔记，但是这个做一个步骤还是很麻烦。
如果可以实现上述功能，就方便很多。
这样，这不仅是个阅读器，而且还是个学习神器。

**Comment by Andy-AO** [comment]
发现竞品Clearly Reader有高亮功能
![image](https://github.com/hewenguang/circle/assets/38101170/70013142-a028-41c5-96f7-5d332dc57f98)

**Comment by hewenguang** [comment]
偏好设置高级设置里开启文本工具组和批注就可以了。不过比较粗糙，新版本开发中了。感谢支持, Circle ***@***.***官网：https://circlereader.com在 2024年2月23日，12:37，Andy AO ***@***.***> 写道：﻿
发现竞品Clearly Reader有笔记功能
image.png (view on web)

**Comment by Andy-AO** [comment]
> 偏好设置高级设置里开启文本工具组和批注就可以了。不过比较粗糙，新版本开发中了。感谢支持, Circle ***@***.***官网：[https://circlereader.com在](https://circlereader.com%E5%9C%A8) 2024年2月23日，12:37，Andy AO ***@***.***> 写道：﻿ 发现竞品Clearly Reader有笔记功能 image.png (view on web) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

谢谢

**Comment by Andy-AO** [comment]
@hewenguang 

![image](https://github.com/hewenguang/circle/assets/38101170/0960b4e2-9300-4bad-9aa2-838c0c59815e)

这个功能开启之后该如何使用呢？

其他的标注软件很多都是选中之后会弹出一个按钮，但是我这里没有发现啊。

![image](https://github.com/hewenguang/circle/assets/38101170/7e10452d-8b4f-464f-9b35-1b5e8a86f96f)

**Comment by hewenguang** [comment]
<img width="1111" alt="截屏2024-02-23 16 26 51" src="https://github.com/hewenguang/circle/assets/38025280/4eeaf59d-ea44-4a84-9f54-ddf7a3021c38">
按照示意图开启即可
