### ISSUE TITLE
Microsoft Edge 及 Firefox 支持

### ISSUE THREAD

**Issue by SylleoYr** [hewenguang/circle#7]
可以上架 Microsoft Edge 扩展商店吗？
还有就是 Firefox 有机会吗？🤣

**Comment by hewenguang** [comment]
感谢反馈，目前产品刚刚起步，我工作之余开发着玩的，后期会考虑其他平台，目前处于打磨阶段。后期牛奶和面包都会有的

**Comment by hewenguang** [comment]
已经更新到 https://github.com/hewenguang/circle/issues/1

**Comment by hewenguang** [comment]
进入[Microsoft Edge 浏览器扩展市场](https://microsoftedge.microsoft.com/addons/detail/circle-%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F%EF%BD%9Creader-mode/hjkjecmcifblnghjpcjaofpakjpgfjio) 安装

进入[Firefox 浏览器扩展市场](https://addons.mozilla.org/zh-CN/firefox/addon/circle-reading-mode/) 安装

进入[Chrome 浏览器扩展市场](https://chrome.google.com/webstore/detail/circle-reader-mode/dhpfcgilccfkodnhbllpiaabofjbjcbg)下载

**Comment by SylleoYr** [comment]
> 
> 
> 进入[Microsoft Edge 浏览器扩展市场](https://microsoftedge.microsoft.com/addons/detail/circle-%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F%EF%BD%9Creader-mode/hjkjecmcifblnghjpcjaofpakjpgfjio) 安装
> 
> 进入[Firefox 浏览器扩展市场](https://addons.mozilla.org/zh-CN/firefox/addon/circle-reading-mode/) 安装
> 
> 进入[Chrome 浏览器扩展市场](https://chrome.google.com/webstore/detail/circle-reader-mode/dhpfcgilccfkodnhbllpiaabofjbjcbg)下载

老哥效率，up！
