### ISSUE TITLE
越改越垃圾

### ISSUE THREAD

**Issue by githubcatheaven** [hewenguang/circle#70]
默认的宽度都调整不了

**Comment by hewenguang** [comment]
![Uploading 截屏2024-03-15 15.15.16.png…]()

**Comment by hewenguang** [comment]
<img width="655" alt="截屏2024-03-15 15 15 16" src="https://github.com/hewenguang/circle/assets/38025280/837ceda2-2733-44a7-9e18-bcea33d923d2">
