### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by leicancun** [hewenguang/circle#8]
大佬你好，我试用了一下Circle，显示效果的确非常棒，希望能支持快捷键调用，自定义框选，期待油猴脚本😁

**Comment by hewenguang** [comment]
满足你！！！下个版本上！！！更新如： https://github.com/hewenguang/circle/issues/1

**Comment by hewenguang** [comment]
v2.0.0 版本已上线自定义框选和快捷键，油猴脚本由于技术限制，暂时无法上线

暮雨 ***@***.***> 于2021年3月4日周四 下午6:30写道：
